package org.galatea.starter.service;

import feign.Feign;
import feign.Headers;
import feign.Param;
import feign.RequestLine;
import feign.jackson.JacksonDecoder;
import feign.jackson.JacksonEncoder;
import java.time.LocalDate;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.galatea.starter.domain.AlphaVantageReturnMessage;
import org.galatea.starter.domain.StockData;
import org.galatea.starter.domain.StockDataMessage;
import org.galatea.starter.domain.rpsy.StockDataRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;


@Slf4j
@Service
public class AlphaVantageService {

  @Value("${alpha-vantage.uri}")
  private String uri;

  @Value("${alpha-vantage.query}")
  private static String query;

  @Autowired
  StockDataRepository repository;


  interface FuseServer {

    @RequestLine("GET /query?function=TIME_SERIES_DAILY&symbol={symbol}&outputsize={size}&apikey=PFPOE75HO1WCKW7H")
    AlphaVantageReturnMessage alphaVantageApiCall(@Param("symbol") String symbol, @Param("size") String outputSize);

  }

  /**
   * Makes api call to Alpha Vantage to retrieve data not persisted in database
   * @param symbol stock symbol
   * @param numDays number of days request is for, used to determine full or compact
   * @return AlphaVantageReturnMessage containing the data from the Alpha Vantage request
   */
  public void alphaVantageCall(String symbol, int numDays, StockDataMessage stockDataMessage, List<String> dates) {
    FuseServer fuseServer = Feign.builder()
        .decoder(new JacksonDecoder())
        .encoder(new JacksonEncoder())
        .target(FuseServer.class, uri);
    log.info("Calling Alpha Vantage for symbol: {} and numDays: {}", symbol, numDays);
    long startTime = System.currentTimeMillis();
    AlphaVantageReturnMessage alphaVantageReturnMessage = fuseServer.alphaVantageApiCall(symbol, (numDays > 100) ? "full" : "compact");
    long endTime = System.currentTimeMillis();
    log.info("Alpha Vantage call completed in: {}ms", endTime-startTime);
    convertToStockDataMessage(alphaVantageReturnMessage, dates, stockDataMessage);
  }

  /**
   * Convert AlphaVantageReturn message generated by  api call to StockDataMessage
   * @param avMessage
   * @param dates
   * @param stockDataMessage
   */
  public void convertToStockDataMessage(AlphaVantageReturnMessage avMessage, List<String> dates, StockDataMessage stockDataMessage) {
    stockDataMessage.setSymbol(avMessage.getMetaData().getSymbol());
    for(String d:dates) {
      stockDataMessage.setTimeSeriesData(d, avMessage.getTimeSeriesData(d));
      repository.save(new StockData(stockDataMessage.getSymbol(), d, avMessage.getTimeSeriesData(d)));
    }

  }
}
