package org.galatea.starter.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializationFeature;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.galatea.starter.domain.AlphaVantageReturnMessage;
import org.galatea.starter.domain.StockData;
import org.galatea.starter.domain.StockDataMessage;
import org.galatea.starter.domain.rpsy.StockDataRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Service which requests data from Alpha Vantage and transforms it to return desired dates
 */
@Slf4j
@Service
public class StockPriceService {

  @Autowired
  StockDataRepository repository;
  @Autowired
  ObjectMapper mapper;
  @Autowired
  AlphaVantageService alphaVantageService;


  public String getPriceData(String symbol, int days) throws JsonProcessingException{

    List<String> dates = getListDates(days);

    StockDataMessage result = databaseCheck(symbol, days, dates);

    if (!dates.isEmpty()) {
      AlphaVantageReturnMessage avMessage = alphaVantageService.alphaVantageCall(symbol, days);
      convertToStockDataMessage(avMessage, dates, result);
    }

//    AlphaVantageReturnMessage trimmedMessage = trimData(result, dates);
    log.info("attempting to convert to json: {}", result.toString());
    String json = messageToJson(result);
//    persistToDatabase(result);
    log.info("json converted {}", json);
    return json;
  }

  private String messageToJson(StockDataMessage message) throws JsonProcessingException{
    try {
      String json = mapper.writeValueAsString(message);
      log.info("object converted to json {}", json);
      log.debug(json);
      return json;
    } catch (JsonProcessingException e) {
      log.error("error converting to json", e);
      throw e;
    }
  }

  public String dumpDatabase(String symbol) throws JsonProcessingException{
    List<StockData> stocks = repository.findByStockSymbol(symbol);
    StockDataMessage message = new StockDataMessage();

    message.setSymbol(symbol);
    for (StockData d:stocks) {
      message.setTimeSeriesData(d.getDate(), d.getPriceData());
    }

    return messageToJson(message);

  }

  /**
   * Determine if data for given symbol is already in database - if so returns the
   * AlphaVantageReturnMessage stored, otherwise, makes a call to alpha vantage and
   * returns result
   * @param symbol
   * @param days
   * @param dates
   * @return
   */
  private StockDataMessage databaseCheck(String symbol, int days, List<String> dates) {
    List<StockData> data = repository.findByStockSymbolAndDateIn(symbol, dates);
    StockDataMessage message = new StockDataMessage();

    message.setSymbol(symbol);
    for (StockData d:data) {
      message.setTimeSeriesData(d.getDate(), d.getPriceData());
      dates.remove(d.getDate());
    }

    return message;
  }

  /**
   * Generate list of desired dates based on number of days requested, excluding weekend dates
   * TODO: exclude holidays from date list
   */
  private List<String> getListDates(int days) {
    LocalDate today = LocalDate.now();
    List<String> dates = new ArrayList<>();
    int j = 0;
    while (dates.size() < days) {
      LocalDate day = today.minusDays(j);
      if (day.getDayOfWeek() != DayOfWeek.SATURDAY && day.getDayOfWeek() != DayOfWeek.SUNDAY) {
        dates.add(day.toString());
      }
      j++;
    }

    return dates;
  }

  //TODO: consider moving to AlphaVantageService

  /**
   * Convert AlphaVantageReturn message generated by  api call to StockDataMessage
   * @param avMessage
   * @param dates
   * @param stockDataMessage
   */
  public void convertToStockDataMessage(AlphaVantageReturnMessage avMessage, List<String> dates, StockDataMessage stockDataMessage) {
    stockDataMessage.setSymbol(avMessage.getMetaData().getSymbol());
    for(String d:dates) {
      stockDataMessage.setTimeSeriesData(d, avMessage.getTimeSeriesData(d));
      repository.save(new StockData(stockDataMessage.getSymbol(), d, avMessage.getTimeSeriesData(d)));
    }

  }

}
