package org.galatea.starter.service;

import com.opengamma.strata.basics.date.HolidayCalendar;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.galatea.starter.CacheConfig;
import org.galatea.starter.domain.AlphaVantageReturnMessage;
import org.galatea.starter.domain.StockDataMessage;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Service which requests data from Alpha Vantage and transforms it to return desired dates.
 */
@Slf4j
@Service
@AllArgsConstructor
public class StockPriceService {

  private final DatabaseService databaseService;
  private final AlphaVantageService alphaVantageService;
  private final HolidayCalendar holidayCalendar;


  /**
   * Given a stock symbol and number of days, returns json containing stock price data for
   * the past n number of days for the given stock.
   * @param symbol stock symbol for which data should be returned
   * @param days number of days for which data should be returned
   * @return string representing json for stock price data
   */
  @Cacheable(CacheConfig.CACHE_ONE)
  public StockDataMessage getPriceData(String symbol, int days) {

    log.info("Retrieving price data for symbol: {} and {} days", symbol, days);
    List<String> dates = getListDates(days);

    StockDataMessage result = databaseService.databaseCheck(symbol, dates);

    List<String> remainingDates = getRemainingDates(result, dates);

    if (!remainingDates.isEmpty()) {
      AlphaVantageReturnMessage avMessage = alphaVantageService.alphaVantageCall(symbol, days);
      convertToStockDataMessage(avMessage, remainingDates, result);
      saveToDatabase(remainingDates, result);
    }

    return result;
  }

  /**
   * Given a stock symbol, returns json containing stock price data for all
   * stored database values for that stock.
   * @param symbol stock symbol for which data should be returned
   * @return string representing json for stock price data
   */
  public StockDataMessage getPriceData(String symbol) {
    log.info("Retrieving all database entries for stock symbol: {}", symbol);
    return databaseService.dumpDatabase(symbol);
  }

  /**
   * Convert AlphaVantageReturn message generated by  api call to StockDataMessage.
   * @param avMessage AlphaVantage message generated by api call
   * @param dates list of relevant dates to be added to stockDataMessage
   * @param stockDataMessage stockDataMessage possibly containing data, to which stock
   *        price data for relevant dates is added
   */
  private void convertToStockDataMessage(AlphaVantageReturnMessage avMessage, List<String> dates,
      StockDataMessage stockDataMessage) {
    stockDataMessage.setSymbol(avMessage.getMetaData().getSymbol());
    for (String d:dates) {
      stockDataMessage.setTimeSeriesData(d, avMessage.getTimeSeriesData(d));
    }
  }

  /**
   * Save data given dates from stockDataMessage to database.
   * @param dates list of relevant dates to be saved
   * @param stockDataMessage contains price data
   */
  private void saveToDatabase(List<String> dates, StockDataMessage stockDataMessage) {
    for (String d:dates) {
      databaseService.save(stockDataMessage.getSymbol(), d, stockDataMessage.getTimeSeriesData(d));
    }
  }

  /**
   * Given a list of dates and a stock data message returns list of dates contained in original
   * list but not stored in stockData Message.
   * @param stockDataMessage data to be checked against
   * @param dates list of dates to see check
   * @return list of dates checked for which data was not stored in stockDataMessage
   */
  private List<String> getRemainingDates(StockDataMessage stockDataMessage, List<String> dates) {
    List<String> remainingDates = new ArrayList<>();

    for (String d:dates) {
      if (!stockDataMessage.getTimeSeriesData().containsKey(d)) {
        remainingDates.add(d);
      }
    }

    return remainingDates;
  }

  /**
   * Generate list of desired dates based on number of days requested, excluding weekend dates,
   * stock market holidays, and stock market closures.
   */
  private List<String> getListDates(int days) {
    LocalDate today = LocalDate.now();
    List<String> dates = new ArrayList<>();
    int numDaysChecked = 0;
    while (dates.size() < days) {
      //increment numDaysChecked regardless of whether date added to list or not
      LocalDate day = today.minusDays(numDaysChecked++);
      if (holidayCalendar.isBusinessDay(day)) {
        dates.add(day.toString());
      }
    }

    return dates;
  }

}
